### ISSUE TITLE
Error when connecting to containerized netbox-mcp-server

### ISSUE THREAD

**Issue by jcollins313** [netboxlabs/netbox-mcp-server#58]
### Steps to Reproduce

When I bring up a web interface to http://<server_ip>:8000/mcp I receive the following:
```
{
  "jsonrpc": "2.0",
  "id": "server-error",
  "error": {
    "code": -32600,
    "message": "Not Acceptable: Client must accept text/event-stream"
  }
}
```

This doesn't seem expected. 
I built the container per the instructions:
# Build the image
`docker build -t netbox-mcp-server:latest .`

I'm running the container with the recommended command:
# Run with HTTP transport (required for Docker containers)
```
docker run --rm \
  -e NETBOX_URL=https://netbox.example.com/ \
  -e NETBOX_TOKEN=<your-api-token> \
  -e TRANSPORT=http \
  -e HOST=0.0.0.0 \
  -e PORT=8000 \
  -p 8000:8000 \
  netbox-mcp-server:latest
```
 I have tried connecting this mcp server to n8n and received an error and would like to know if I'm missing something.

### Expected Behavior

I am expecting some success language when connecting to http://<server_ip>:8000/mcp

### Observed Behavior

When I bring up a web interface to http://<server_ip>:8000/mcp I receive the following:
```
{
  "jsonrpc": "2.0",
  "id": "server-error",
  "error": {
    "code": -32600,
    "message": "Not Acceptable: Client must accept text/event-stream"
  }
}
```

**Comment by abubnalitic-nbl** [comment]
Hi @DharmaBytesX, 

Sorry for the delay in response. I have pushed in a fix for this but I'm not running N8N. Are you able to test or confirm that the branch in the PR resolves the problem?
https://github.com/netboxlabs/netbox-mcp-server/pull/61

Best,
Anton

**Comment by X-Coder** [comment]
The PR didn't fix it for me, I still get the same error message with the same setup from https://github.com/netboxlabs/netbox-mcp-server/issues/58#issuecomment-3607091269

Error: 
```can't access property "inputType", mapTypes[type] is undefined```

This is how I tested the PR:
```
git fetch origin pull/61/head:pull_61
git checkout pull_61
docker build -t netbox-mcp-server:latest . --no-cache
docker run \                                         
  -e NETBOX_URL=https://example.com/ \
  -e NETBOX_TOKEN=EXAMPLE \
  -e TRANSPORT=http \
  -e HOST=0.0.0.0 \
  -e LOG_LEVEL=DEBUG \
  -e VERIFY_SSL=false \
  -p 8000:8000 \
  netbox-mcp-server:latest
```

**Comment by X-Coder** [comment]
Thank you for your work.

The updated PR #61 fixed the error message for me and n8n shows now the related input fields for the tool.

I just had some troubles building the new docker image with it (docker build -t netbox-mcp-server:my-latest .)
It failed compiling pydantic-core, I downgraded to python:3.13-alpine3.20 in Dockerfile, then it worked.

**Comment by abubnalitic-nbl** [comment]
Ultimately, the fix that we implemented addresses a bug in the N8N UI but the mcp server will still work. It's only the test client buttons that are affected. Given this, it's not worth maintaining a fix for this upstream bug. We have closed the PR https://github.com/netboxlabs/netbox-mcp-server/pull/123 and will leave the branch open if it is still needed https://github.com/netboxlabs/netbox-mcp-server/tree/feat/n8n-compat-optin
